import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '@/componenets/Nabar'
import data from "../data/data.json";
import Product from '@/componenets/Product';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Shopping Cart</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <section className="container mx-auto">
        <h1 className="text-4xl mt-4 text-center">Our Products</h1>
        <div className="mt-4 grid grid-cols-1 md:grid-cols-3 gap-4">
          {data.map((product) => (
            <Product product={product} />
          ))}
        </div>
      </section>
    </>
  );
}
